Create multiple records
sailscastshq/captain-vane pull request #2
Opened 2022-03-11 19:07 UTC by haastrupea

Fixes #1 💯  Create multiple records with the vane helper

2022-03-16 13:01 UTC, DominusKelvin requested changes
Looking good @haastrupea. Thanks for taking the time to submit this PR. Do you think we can rename `totalRecord` to `count` and I like that it is defaulting to 1. I'm looking at simplifying the code and just default to using .createEach even if the caller want's a single record. What do you think?

2022-03-17 08:43 UTC, haastrupea commented
> Looking good @haastrupea. Thanks for taking the time to submit this PR. Do you think we can rename `totalRecord` to `count` and I like that it is defaulting to 1. I'm looking at simplifying the code and just default to using .createEach even if the caller want's a single record. What do you think?

Thank you. I thought about it too, it is actually a great way to simplify the code

2022-03-17 09:04 UTC, haastrupea commented
> Looking good @haastrupea. Thanks for taking the time to submit this PR. Do you think we can rename `totalRecord` to `count` and I like that it is defaulting to 1. I'm looking at simplifying the code and just default to using .createEach even if the caller want's a single record. What do you think?

Done

2022-03-19 05:32 UTC, DominusKelvin commented
@haastrupea this is getting exciting. I was wondering if we can smartly return an object if the record created was 1 and we can take that cognitive load off the user. What do you think?

Also, can you attach a screenshot of this working on your machine?

2022-03-19 07:20 UTC, haastrupea commented
> @haastrupea this is getting exciting. I was wondering if we can smartly return an object if the record created was 1 and we can take that cognitive load off the user. What do you think?
> 
> Also, can you attach a screenshot of this working on your machine?



Well, I thought about it too but you know the rule, always keep it simple. Now that you asked, it is done.
Just so you know for readability I decided to go with the `if` block for the logic instead of a `ternary` operator. if that is okay.

2022-05-09 23:17 UTC, DominusKelvin commented
Thanks @haastrupea

2022-05-09 23:17 UTC, DominusKelvin approved these changes
Great job on this one

2022-05-09 23:17 UTC, DominusKelvin commented on helper/vane.js
> +    }
`return await model.create(initialValues).fetch()`

2022-05-09 23:17 UTC, merged